/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chats;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author EGYPT
 */
public class Chat_Server extends javax.swing.JFrame {

    /**
     * Creates new form Chat_Server
     */
    //what is the difference between serversocket and the socket
    static ServerSocket server;   //class bystana(bysta2bel) client soct yakalemo         static 3la4an el main
    static Socket client;        //de class byb3at lel server soct
    static DataInputStream din;
    static DataOutputStream dout;
    
    
    public Chat_Server() {
        initComponents(); //to make an intialization for component
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Msg_Area = new javax.swing.JTextArea();
        Msg_Text = new javax.swing.JTextField();
        Msg_Send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Msg_Area.setColumns(20);
        Msg_Area.setRows(5);
        jScrollPane1.setViewportView(Msg_Area);

        Msg_Text.setText("jTextField1");
        Msg_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Msg_TextActionPerformed(evt);
            }
        });

        Msg_Send.setText("jButton1");
        Msg_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Msg_SendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Msg_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Msg_Send, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Msg_Text)
                    .addComponent(Msg_Send, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Msg_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Msg_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Msg_TextActionPerformed
    //we can make action listener insted of textaction performed

    private void Msg_SendActionPerformed(java.awt.event.ActionEvent evt) {// for the bottom (key)
//GEN-FIRST:event_Msg_SendActionPerformed
 try{      //3la4an law fe error yt4al
     String Msgout = "";//message out ..elmessage ela ana hb3atha lel client
     Msgout = Msg_Text.getText().trim();// write here...get text 3lshan akteb ....trim eltarteb m4 3ayz ay haga ttmes7
     dout.writeUTF(Msgout); }// btsma7 any akteb ay haga ay language....dout de hatb3at 
 catch(Exception e)
 {                 }
  // TODO add your handling code here:
    }//GEN-LAST:event_Msg_SendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Server().setVisible(true);
            }
        });
        
        String Msgin = " "; //tst2abl elkalam mn el client
        try{
            
            server = new ServerSocket(1201);  //port number lazem yb2a mawgod 3and eltany
            client = server.accept();        //cient yakhale el server ya2bal
            din = new DataInputStream(client.getInputStream());//bastabel elkalem mn elclient...
            dout =new DataOutputStream(client.getOutputStream());//hatb3at elkalam lel client 
            while(!Msgin.equals("Exit"))//tol ma el program 4a8al yastabel el messages el btdokol
            { Msgin = din.readUTF();//tstabel w tekra2 el kalam el bytba3t mn client
            Msg_Area.setText(Msg_Area.getText().trim()+"\n"+Msgin); //al4an el fram ..hatgeb eltext beltarteb w , hatemsa7 el ablaha
            }
        }
            catch (Exception e)
            {          }
        }
        
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea Msg_Area;
    private javax.swing.JButton Msg_Send;
    private javax.swing.JTextField Msg_Text;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
